/*
 Python Macro Language for Dragon NaturallySpeaking
	(c) Copyright 1999 by Joel Gould
	Portions (c) Copyright 1999 by Dragon Systems, Inc.

 stdafx.cpp (generated by Visual C++)
	source file that includes just the standard includes EnableNL.pch will
	be the pre-compiled header stdafx.obj will contain the pre-compiled type
	information 
*/

#include "stdafx.h"

